# -*- coding: utf-8 -*-
"""volume_of_sphere

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YnDWTouvja9hWX1g7fS65TCYYvm3VR7k
"""

def calculate_volume_of_sphere(radius):
  pi = 3.14
  volume = (4/3) * pi * (radius**3)
  return volume

print(calculate_volume_of_sphere(30))
print(calculate_volume_of_sphere(40))